# Site settings
# in the templates available like {{ site.myvariable }}.
title: 口技破击 
email: your-email@domain.com
brand: white
headline: Inventor, Engineer and Futurist
description: > # this means to ignore newlines until "baseurl:"
  New Site
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://example.com" # the base hostname & protocol for your site
copyright: 2016 Whatever Company, Inc. All Rights Reserved.

# Build settings
markdown: kramdown

# Account ids
snapwidget: 247552

# Contacts
email: white520250@gmail.com
phone: 155-9689-3590

# Tracking
googleAnalitycsID: UA-83933844-1

